// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlcmaklcoyilhluprojo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsY21ha2xjb3lpbGhsdXByb2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NzA5NTQsImV4cCI6MjA4NzM0Njk1NH0.4QsfbiOPnq_6IXf17uyEaFiZw3JX-Zj0McxoQGClcFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});